set(ASSETS_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/assets)
set(ASSETS_DEST_PARENT_DIR ${CMAKE_CURRENT_BINARY_DIR}/)
set(ASSETS_DEST_DIR ${ASSETS_DEST_PARENT_DIR}/assets)

message(STATUS "REMOVING FOLDER " ${ASSETS_DEST_DIR})
file(REMOVE_RECURSE ${ASSETS_DEST_DIR})
message(STATUS "COPYING FILES FROM " ${ASSETS_SOURCE_DIR} " TO " ${ASSETS_DEST_PARENT_DIR})
file(COPY ${ASSETS_SOURCE_DIR} DESTINATION ${ASSETS_DEST_PARENT_DIR})